version: "3.9"
services:
  web:
    build:
      context: .
    command: rails s -p 3000 -b '0.0.0.0' 
    volumes:
      - .:/code
    ports:
      - 3000:3000
  db:
    image: mysql:8
    command: [--default-authentication-plugin=mysql_native_password, --sql-mode=NO_ENGINE_SUBSTITUTION]
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=se_dev
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
